// app/layout.js
import "./globals.css";

import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
export const metadata = {
  title: "Path Recharge",
  description:
    "Path Recharge: Experts in highway logistics, wayside amenities, GFRP bars, and crash barriers. Serving Bangalore and beyond.",
  keywords:
    "Path Recharge, highway , toll plaza , logistics, wayside amenities, GFRP bars, crash barriers",
  author: "Path Recharge",
  viewport: "width=device-width, initial-scale=1.0",
  robots: "index, follow",
  openGraph: {
    title: "Path Recharge - Highway & Logistics Solutions",
    description:
      "Path Recharge: Experts in highway and toll plaza , wayside amenities, GFRP bars, and crash barriers.",
    type: "website",
    url: "https://www.pathrecharge.com", // replace with your actual URL
    site_name: "Path Recharge",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Google Fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400..900&family=Oswald:wght@200..700&family=Work+Sans:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Epunda+Sans:ital,wght@0,300..900;1,300..900&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Epunda+Sans:ital,wght@0,300..900;1,300..900&family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />

        {/* SEO Meta Tags */}
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <meta name="keywords" content={metadata.keywords} />
        <meta name="author" content={metadata.author} />
        <meta name="viewport" content={metadata.viewport} />
        <meta name="robots" content={metadata.robots} />

        {/* Open Graph / Social Sharing */}
        <meta property="og:title" content={metadata.openGraph.title} />
        <meta property="og:description" content={metadata.openGraph.description} />
        <meta property="og:type" content={metadata.openGraph.type} />
        <meta property="og:url" content={metadata.openGraph.url} />
        <meta property="og:site_name" content={metadata.openGraph.site_name} />
      </head>

      <body className="w-full overflow-x-hidden font-oswald pt-[90px]  ">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}




// // app/layout.js
// import "./globals.css";
// import Navbar from "./components/Navbar";
// import Footer from "./components/Footer";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <head>
//         {/* Google Fonts */}
//         <link rel="preconnect" href="https://fonts.googleapis.com" />
//         <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />

//         <link
//           href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400..900&family=Oswald:wght@200..700&family=Work+Sans:ital,wght@0,100..900;1,100..900&display=swap"
//           rel="stylesheet"
//         />

//         <link
//           href="https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap"
//           rel="stylesheet"
//         />

//         <link
//           href="https://fonts.googleapis.com/css2?family=Epunda+Sans:ital,wght@0,300..900;1,300..900&display=swap"
//           rel="stylesheet"
//         />

//         <link
//           href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Epunda+Sans:ital,wght@0,300..900;1,300..900&family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&display=swap"
//           rel="stylesheet"
//         />
//       </head>

//       <body className="w-full overflow-x-hidden font-oswald pt-[90px]">
//         <Navbar />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }
